import { readFileSync, writeFileSync, copyFileSync, existsSync, readdirSync } from "fs";
import { dirname, join } from "path";
import vm from "vm";
import { CrossSeedConfig, CrossSeedConfigSchema } from "@/types/config";

/**
 * Parse the cross-seed config.js file
 */
export function parseConfig(configPath: string): CrossSeedConfig {
  if (!existsSync(configPath)) {
    throw new Error(`Config file not found: ${configPath}`);
  }

  const content = readFileSync(configPath, "utf-8");

  // Create a sandbox with module.exports
  const sandbox = {
    module: { exports: {} as Record<string, unknown> },
    exports: {} as Record<string, unknown>,
  };

  // Create context and run the config file
  const context = vm.createContext(sandbox);

  try {
    vm.runInContext(content, context, {
      timeout: 1000,
      filename: configPath,
    });
  } catch (error) {
    throw new Error(
      `Failed to parse config file: ${error instanceof Error ? error.message : "Unknown error"}`
    );
  }

  // Get the exported config
  const rawConfig = sandbox.module.exports;

  // Validate and return
  const result = CrossSeedConfigSchema.safeParse(rawConfig);

  if (!result.success) {
    throw new Error(`Invalid config: ${result.error.message}`);
  }

  return result.data;
}

/**
 * Generate config file content from config object
 */
export function generateConfigFile(config: CrossSeedConfig): string {
  const timestamp = new Date().toISOString();

  return `// Cross-seed configuration
// Generated by CrossSeed UI on ${timestamp}
// Manual edits will be preserved on next UI save

module.exports = ${JSON.stringify(config, null, 2)};
`;
}

/**
 * Write config to file with backup
 */
export function writeConfig(configPath: string, config: CrossSeedConfig): void {
  // Validate config before writing
  const result = CrossSeedConfigSchema.safeParse(config);
  if (!result.success) {
    throw new Error(`Invalid config: ${result.error.message}`);
  }

  // Create backup if file exists
  if (existsSync(configPath)) {
    const backupDir = dirname(configPath);
    const backupPath = join(backupDir, `config.js.backup.${Date.now()}`);
    copyFileSync(configPath, backupPath);
  }

  // Generate and write new config
  const content = generateConfigFile(result.data);
  writeFileSync(configPath, content, "utf-8");
}

/**
 * Check if config file exists
 */
export function configExists(configPath: string): boolean {
  return existsSync(configPath);
}

/**
 * Get list of config backups
 */
export function getConfigBackups(configPath: string): string[] {
  const dir = dirname(configPath);

  try {
    const files = readdirSync(dir);
    return files
      .filter((f) => f.startsWith("config.js.backup."))
      .sort()
      .reverse();
  } catch {
    return [];
  }
}
